### ISSUE TITLE
No ability to reset colors

### ISSUE THREAD

**Issue by sirnacnud** [k0nserv/luft#13]
After changing the colors in the Preferences menu, there is no way to reset the colors back to their default values. I even tried uninstalling the plugin and reinstalling it through Alcatraz. I'm guessing the settings didn't get cleared on uninstall.

It would be nice to have a reset button in the Preferences.

**Comment by k0nserv** [comment]
Great suggestion :) I think @bogren had something like that in his initial version of the preferences dialoge?

**Comment by bogren** [comment]
Idd great. Yes, I did :smiley: Adding the button again later today :+1:

**Comment by k0nserv** [comment]
Resolved in #15

**Comment by sirnacnud** [comment]
Thanks for adding this!

**Comment by bogren** [comment]
Np :smiley:
