### ISSUE TITLE
How to remove luft

### ISSUE THREAD

**Issue by numton** [k0nserv/luft#16]
..

**Comment by bogren** [comment]
Alt 1. If you installed Luft using Alcatraz you can open package manager (cmd+9) and uninstall. 

Alt 2. All plugins can be found and removed from this folder `~/Library/Application\ Support/Developer/Shared/Xcode/Plug-ins`. Paste this in your terminal to remove Luft
`rm -rf ~/Library/Application\ Support/Developer/Shared/Xcode/Plug-ins/Luft.xcplugin`
