### ISSUE TITLE
Xcode 8 doesn't load plugins

### ISSUE THREAD

**Issue by sirnacnud** [k0nserv/luft#28]
It looks like Xcode 8 removed support for loading plugins and added the ability to create an _Xcode Source Editor Extension_ as the official way to add functionality. There is a discussion on [Alcatraz](https://github.com/alcatraz/Alcatraz/issues/475) about the issue.

Any thoughts on converting Luft to an extension?

**Comment by bogren** [comment]
We talked about it, but as far as I understand there is no support for coloring the side bar. @k0nserv filed a radar, and there are a few others 😃

**Comment by k0nserv** [comment]
Yeah Luft can't be implement as a Xcode Source Editor as it currently stands. I've raised several radars for functionality that would be required to do so. I don't personally recommend stripping code signing from Xcode, but there are tools out there to do so which allows running Luft and other old style plugins under Xcode 8.

**Comment by k0nserv** [comment]
These are the radars
- https://openradar.appspot.com/radar?id=5503702324477952
- https://openradar.appspot.com/radar?id=4985435868626944
- https://openradar.appspot.com/radar?id=5001777682317312

in case you want to dupe them

**Comment by k0nserv** [comment]
@bogren added supported for running Luft in Xcode 8 with code sining stripped https://github.com/k0nserv/luft/pull/29
